apiVersion: v1
kind: Pod
metadata:
  name: k8app
  labels:
    app: k8app
spec:
  containers:
  - name: k8app
    image: skyscreen/ncv:app1.1
    command:
    - /tmp/servlet/start.sh
    ports:
    - containerPort: 8080
